#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:/opt/gwt-linux-1.0.20/gwt-user.jar:/opt/gwt-linux-1.0.20/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.benjie.cheech;
