#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:/opt/gwt-linux-1.0.20/gwt-user.jar:/opt/gwt-linux-1.0.20/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.benjie.cheech/cheech.html;
