#!/bin/sh
#
# Build a relocatable Mac OS X .app bundle for the cheech GUI.
#
# This is invoked by "make bundle" (see the top-level Makefile.am).  It
# copies the already-built GUI into a Cheech.app skeleton, copies the
# program's data files into Contents/Resources (where the CoreFoundation
# code in game_images.cc looks for them, i.e. configure --enable-macos-app),
# vendors the non-system dynamic libraries with dylibbundler and ad-hoc
# code signs the result.
#
# Requirements:
#   * configured with --enable-macos-app
#   * dylibbundler in PATH  (brew install dylibbundler)

set -eu

srcdir=""
builddir=""
name="Cheech"
version="0.0"

while [ $# -gt 0 ]; do
	case "$1" in
		--srcdir)   srcdir="$2"; shift 2 ;;
		--builddir) builddir="$2"; shift 2 ;;
		--name)     name="$2"; shift 2 ;;
		--version)  version="$2"; shift 2 ;;
		*) echo "make-bundle.sh: unknown option: $1" >&2; exit 2 ;;
	esac
done

if [ -z "$srcdir" ] || [ -z "$builddir" ]; then
	echo "make-bundle.sh: --srcdir and --builddir are required" >&2
	exit 2
fi

srcdir=$(cd "$srcdir" && pwd)
builddir=$(cd "$builddir" && pwd)

bin="$builddir/src/cheech"
if [ ! -x "$bin" ]; then
	echo "make-bundle.sh: $bin not found; run 'make' first" >&2
	exit 1
fi

if ! grep -q '^#define MACOS_APP 1' "$builddir/config.h" 2>/dev/null; then
	echo "make-bundle.sh: this build was not configured for a Mac app bundle." >&2
	echo "              Re-run configure with --enable-macos-app and rebuild." >&2
	exit 1
fi

if ! command -v dylibbundler >/dev/null 2>&1; then
	echo "make-bundle.sh: dylibbundler not found; install it with 'brew install dylibbundler'" >&2
	exit 1
fi

app="$builddir/$name.app"
macos="$app/Contents/MacOS"
res="$app/Contents/Resources"
frameworks="$app/Contents/Frameworks"

echo "make-bundle.sh: assembling $app"
rm -rf "$app"
mkdir -p "$macos" "$res" "$frameworks"

# The real executable and a tiny launcher that sets up the GTK runtime
# environment before exec'ing it.  CFBundleExecutable points at the
# launcher; CoreFoundation still resolves the enclosing .app as the main
# bundle when the real binary runs.
cp "$bin" "$macos/cheech-bin"
chmod 755 "$macos/cheech-bin"

# Pixmaps (game_images.cc reads these straight from Contents/Resources).
for png in "$srcdir"/pixmaps/*.png; do
	[ -e "$png" ] || continue
	cp "$png" "$res/"
done

# Application icon, generated from the artwork that ships with the old
# Xcode project, if it is available.
icon_file=""
icon_src="$srcdir/cheech/cheech/Assets.xcassets/AppIcon.appiconset/cheechApp128.png"
if [ -f "$icon_src" ] && command -v sips >/dev/null 2>&1; then
	if sips -s format icns "$icon_src" --out "$res/$name.icns" >/dev/null 2>&1; then
		icon_file="$name.icns"
	fi
fi

# GTK/GLib runtime data.  A modest subset (schemas and the hicolor icon
# theme) is enough for this application; the GTK 2 default theme is
# compiled into the library and PNG loading is built into gdk-pixbuf.
brew_prefix=""
if command -v brew >/dev/null 2>&1; then
	brew_prefix=$(brew --prefix 2>/dev/null || true)
fi
if [ -z "$brew_prefix" ] && command -v pkg-config >/dev/null 2>&1; then
	# Derive the Homebrew root from a pkg-config prefix (e.g.
	# /opt/homebrew/Cellar/gtk+/2.24.33_2 -> /opt/homebrew).
	for m in gtk+-2.0 glib-2.0 gdk-pixbuf-2.0; do
		p=$(pkg-config --variable=prefix "$m" 2>/dev/null || true)
		[ -n "$p" ] || continue
		case "$p" in
			*/Cellar/*) brew_prefix=${p%%/Cellar/*} ;;
			*)          brew_prefix=$p ;;
		esac
		break
	done
fi

if [ -n "$brew_prefix" ] && [ -d "$brew_prefix/share" ]; then
	mkdir -p "$res/share"
	for d in glib-2.0/schemas icons themes; do
		if [ -d "$brew_prefix/share/$d" ]; then
			mkdir -p "$res/share/$(dirname "$d")"
			cp -R "$brew_prefix/share/$d" "$res/share/$d"
		fi
	done
	if command -v glib-compile-schemas >/dev/null 2>&1 && [ -d "$res/share/glib-2.0/schemas" ]; then
		glib-compile-schemas "$res/share/glib-2.0/schemas" 2>/dev/null || true
	fi

	# gdk-pixbuf loaders.  PNG support is built into the library, but
	# bundle the loader modules too so other image formats keep working.
	moddir=$(ls -d "$brew_prefix"/lib/gdk-pixbuf-2.0/*/ 2>/dev/null | head -1 || true)
	moddir=${moddir%/}
	if [ -n "$moddir" ] && [ -d "$moddir/loaders" ]; then
		dest="$res/lib/gdk-pixbuf-2.0"
		mkdir -p "$dest"
		cp "$moddir/loaders.cache" "$dest/loaders.cache"
		cp -R "$moddir/loaders" "$dest/loaders"
		sed "s|$moddir/loaders|$dest/loaders|g" "$dest/loaders.cache" > "$dest/loaders.cache.tmp" && \
			mv "$dest/loaders.cache.tmp" "$dest/loaders.cache"
		for so in "$dest/loaders/"*.so; do
			[ -e "$so" ] || continue
			dylibbundler -b -of -x "$so" -d "$frameworks" \
				-p "@executable_path/../Frameworks" >/dev/null 2>&1 || true
		done
	fi
fi

# Launcher script.
cat > "$macos/cheech" <<EOF
#!/bin/sh
# Generated by cheech's make bundle.  Sets up the GTK runtime environment
# so the bundled libraries and data are used, then runs the game.
bundle="\$(cd "\$(dirname "\$0")/../.." && pwd)"
resources="\$bundle/Contents/Resources"

GTK_DATA_PREFIX="\$resources"
GTK_EXE_PREFIX="\$resources"
GTK_PATH="\$resources"
XDG_DATA_DIRS="\$resources/share${brew_prefix:+:$brew_prefix/share}"
export GTK_DATA_PREFIX GTK_EXE_PREFIX GTK_PATH XDG_DATA_DIRS

if [ -f "\$resources/lib/gdk-pixbuf-2.0/loaders.cache" ]; then
	GDK_PIXBUF_MODULE_FILE="\$resources/lib/gdk-pixbuf-2.0/loaders.cache"
	export GDK_PIXBUF_MODULE_FILE
fi
if [ -d "\$resources/share/glib-2.0/schemas" ]; then
	GSETTINGS_SCHEMA_DIR="\$resources/share/glib-2.0/schemas"
	export GSETTINGS_SCHEMA_DIR
fi

exec "\$bundle/Contents/MacOS/cheech-bin" "\$@"
EOF
chmod 755 "$macos/cheech"

# Info.plist.
cat > "$app/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>cheech</string>
	<key>CFBundleIdentifier</key>
	<string>com.octopilot.cheech</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$name</string>
	<key>CFBundleDisplayName</key>
	<string>$name</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$version</string>
	<key>CFBundleVersion</key>
	<string>$version</string>
	<key>CFBundleIconFile</key>
	<string>$icon_file</string>
	<key>LSMinimumSystemVersion</key>
	<string>11.0</string>
	<key>NSHighResolutionCapable</key>
	<true/>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
</dict>
</plist>
EOF

# Bundle the dynamic libraries.  dylibbundler walks the dependency graph,
# copies each non-system library into Contents/Frameworks and rewrites the
# install names to point at @executable_path/../Frameworks.
echo "make-bundle.sh: bundling libraries with dylibbundler"
dylibbundler -b -cd \
	-x "$macos/cheech-bin" \
	-d "$frameworks" \
	-p "@executable_path/../Frameworks"

# Ad-hoc code signature so macOS is happy to launch the bundle locally.
if command -v codesign >/dev/null 2>&1; then
	codesign --force --deep --sign - "$app" >/dev/null 2>&1 || \
		echo "make-bundle.sh: warning: ad-hoc codesign failed (the app still runs locally)" >&2
fi

echo "make-bundle.sh: done: $app"
