## Process this file with automake to produce Makefile.in

ajaximagedir = $(datadir)/$(PACKAGE)/cheechweb/images

dist_ajaximage_DATA = \
	cheech.png \
	hole-hi.png \
	hole.png \
	peg-black-hi.png \
	peg-black.png \
	peg-blue-hi.png \
	peg-blue.png \
	peg-green-hi.png \
	peg-green.png \
	peg-orange-hi.png \
	peg-orange.png \
	peg-purple-hi.png \
	peg-purple.png \
	peg-red-hi.png \
	peg-red.png \
	peg-white-hi.png \
	peg-white.png \
	peg-yellow-hi.png \
	peg-yellow.png
