CC = gcc
FLAGS = -g -Wall -mno-cygwin -mcpu=pentium -DGNET_EXPERIMENTAL=1
LINK =  -lgnet-2.0 -lglib-2.0-0 -lws2_32
INC = -I../glib -I. -I../gnet -L../glib -L../gnet
all:
	$(CC) $(FLAGS) $(INC) base64_test.c -o base64_test $(LINK)
	$(CC) $(FLAGS) $(INC) hash_test.c -o hash_test $(LINK)
	$(CC) $(FLAGS) $(INC) inetaddr_test.c -o inetaddr_test $(LINK)
	$(CC) $(FLAGS) $(INC) unpack_test.c -o unpack_test $(LINK)
	$(CC) $(FLAGS) $(INC) uri_test.c -o uri_test $(LINK)
	$(CC) $(FLAGS) $(INC) pack_test.c -o pack_test $(LINK)