// generated 2006/2/17 12:05:05 PST by benjie@paddy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/benjie/projects/cheech/cheech.glade
// for gtk 2.8.6 and gtkmm 2.8.0
//
// Please modify the corresponding derived classes in ./src/about_win.hh and./src/about_win.cc

#ifndef _ABOUT_WIN_GLADE_HH
#  define _ABOUT_WIN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>

class about_win_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        
        about_win_glade();
        
        ~about_win_glade();
private:
        virtual void on_close_button_clicked() = 0;
};
#endif
