// generated 2006/2/17 12:05:05 PST by benjie@paddy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/benjie/projects/cheech/cheech.glade
// for gtk 2.8.6 and gtkmm 2.8.0
//
// Please modify the corresponding derived classes in ./src/color_win.hh and./src/color_win.cc

#ifndef _COLOR_WIN_GLADE_HH
#  define _COLOR_WIN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/label.h>
#include <gtkmm/radiobutton.h>

class color_win_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Label * change_label;
        class Gtk::RadioButton * orange;
        class Gtk::RadioButton * yellow;
        class Gtk::RadioButton * white;
        class Gtk::RadioButton * blue;
        class Gtk::RadioButton * purple;
        class Gtk::RadioButton * black;
        class Gtk::RadioButton * red;
        class Gtk::RadioButton * green;
        
        color_win_glade();
        
        ~color_win_glade();
private:
        virtual void on_color_cancel_button_clicked() = 0;
        virtual void on_change_button_clicked() = 0;
};
#endif
