// generated 2006/4/7 0:19:22 EST by benjie@paddy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/benjie/projects/cheech/cheech.glade
// for gtk 2.8.6 and gtkmm 2.8.0
//
// Please modify the corresponding derived classes in ./src/main_win.hh and./src/main_win.cc

#ifndef _MAIN_WIN_GLADE_HH
#  define _MAIN_WIN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/menuitem.h>
#include <gtkmm/imagemenuitem.h>
#include "game_view.hh"
#include "GtkImage.hh"
#include <gtkmm/label.h>
#include <gtkmm/textview.h>
#include <gtkmm/entry.h>

class main_win_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::MenuItem * new_game;
        class Gtk::MenuItem * end_game;
        class Gtk::MenuItem * join_game;
        class Gtk::MenuItem * leave_game;
        class Gtk::MenuItem * game_settings;
        class Gtk::MenuItem * rotate;
        class Gtk::MenuItem * shuffle;
        class Gtk::MenuItem * restart_game;
        class Gtk::MenuItem * restart_submenu;
        class Gtk::ImageMenuItem * undo;
        class Gtk::ImageMenuItem * redo;
        class Gtk::MenuItem * show_last_move;
        class Gtk::MenuItem * change_name;
        class Gtk::MenuItem * change_color;
        class Gtk::MenuItem * add_computer_player;
        class Gtk::MenuItem * remove_computer_players;
        class Gtk::MenuItem * setup_computer_player;
        class game_view * game_view;
        class GtkImage * logo;
        class Gtk::Label * rule_label;
        class Gtk::Label * player_name1;
        class Gtk::Label * player_name2;
        class Gtk::Label * player_name3;
        class Gtk::Label * player_name4;
        class Gtk::Label * player_name5;
        class Gtk::Label * player_name6;
        class GtkImage * player_peg1;
        class GtkImage * player_peg2;
        class GtkImage * player_peg3;
        class GtkImage * player_peg4;
        class GtkImage * player_peg5;
        class GtkImage * player_peg6;
        class Gtk::Label * move_counter;
        class Gtk::TextView * message_view;
        class Gtk::Entry * chat_entry;
        
        main_win_glade();
        
        ~main_win_glade();
private:
        virtual void on_new_game_activate() = 0;
        virtual void on_end_game_activate() = 0;
        virtual void on_join_game_activate() = 0;
        virtual void on_leave_game_activate() = 0;
        virtual void on_game_settings_activate() = 0;
        virtual void on_rotate_activate() = 0;
        virtual void on_shuffle_activate() = 0;
        virtual void on_restart_game_activate() = 0;
        virtual void on_quit_activate() = 0;
        virtual void on_undo_activate() = 0;
        virtual void on_redo_activate() = 0;
        virtual void on_show_last_move_activate() = 0;
        virtual void on_cut_activate() = 0;
        virtual void on_copy_activate() = 0;
        virtual void on_paste_activate() = 0;
        virtual void on_delete_activate() = 0;
        virtual void on_change_name_activate() = 0;
        virtual void on_change_color_activate() = 0;
        virtual void on_add_computer_player_activate() = 0;
        virtual void on_remove_computer_players_activate() = 0;
        virtual void on_setup_computer_player_activate() = 0;
        virtual void on_how_to_play_activate() = 0;
        virtual void on_about_activate() = 0;
        virtual void on_chat_entry_activate() = 0;
};
#endif
