// generated 2006/4/7 0:19:22 EST by benjie@paddy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/benjie/projects/cheech/cheech.glade
// for gtk 2.8.6 and gtkmm 2.8.0
//
// Please modify the corresponding derived classes in ./src/main_win.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION > 2 || (GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2)
//#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "main_win_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/menuitem.h>
#include <gtkmm/menu.h>
#include <gtkmm/imagemenuitem.h>
#include <gtkmm/image.h>
#include <gtkmm/menubar.h>
#include <gtkmm/separatormenuitem.h>
#include <gtkmm/overlay.h>
#include <gtkmm/box.h>
#include <gtkmm/label.h>
#include <gtkmm/table.h>
#include <gtkmm/scrolledwindow.h>
#include <gtkmm/paned.h>
#include <gtkmm/statusbar.h>
#include <gtkmm/cssprovider.h>
#include <gtkmm/stylecontext.h>
#include <gdkmm/screen.h>
#include "game_images.hh"

static const double PEG_SWATCH_PI = 3.14159265358979;

PegColorSwatch::PegColorSwatch() : _color(0)
{
   set_size_request(18, 18);
}

void PegColorSwatch::set_color(int color)
{
   _color = color;
   queue_draw();
}

void PegColorSwatch::clear()
{
   _color = 0;
   queue_draw();
}

bool PegColorSwatch::on_draw(const Cairo::RefPtr<Cairo::Context>& cr)
{
   if (_color <= 0)
      return true;

   double w = get_width();
   double h = get_height();
   double r = (w < h ? w : h) / 2.0 - 1.0;
   if (r <= 0)
      return true;
   double cx = w / 2.0;
   double cy = h / 2.0;

   Gdk::RGBA fill = GameImages::get_peg_fill(_color);
   Gdk::RGBA edge = GameImages::get_peg_edge(_color);

   cr->set_source_rgb(edge.get_red(), edge.get_green(), edge.get_blue());
   cr->arc(cx, cy, r, 0, 2 * PEG_SWATCH_PI);
   cr->fill();

   cr->set_source_rgb(fill.get_red(), fill.get_green(), fill.get_blue());
   cr->arc(cx, cy, r * 0.88, 0, 2 * PEG_SWATCH_PI);
   cr->fill();

   cr->set_source_rgba(1.0, 1.0, 1.0, 0.35);
   cr->arc(cx - r * 0.28, cy - r * 0.34, r * 0.30, 0, 2 * PEG_SWATCH_PI);
   cr->fill();

   return true;
}

main_win_glade::main_win_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{

   Gtk::Window *main_win = this;
   gmm_data = new GlademmData(get_accel_group());
   new_game = NULL;
   end_game = NULL;

   Gtk::MenuItem *separator4 = NULL;
   join_game = NULL;
   leave_game = NULL;
   Gtk::MenuItem *separatormenuitem1 = NULL;
   game_settings = NULL;
   rotate = NULL;
   shuffle = NULL;
   restart_game = NULL;
   Gtk::Menu *restart_submenu_menu = Gtk::manage(new class Gtk::Menu());
   restart_submenu = NULL;
   Gtk::MenuItem *   separator7 = NULL;
   Gtk::ImageMenuItem *quit = NULL;
   Gtk::Menu *menuitem1_menu = Gtk::manage(new class Gtk::Menu());
   Gtk::MenuItem *menuitem1 = NULL;
   Gtk::Image *image46 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-undo"), Gtk::IconSize(1)));
   undo = NULL;
   Gtk::Image *image47 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-redo"), Gtk::IconSize(1)));
   redo = NULL;
   show_last_move = NULL;
   Gtk::MenuItem *separator5 = NULL;
   Gtk::ImageMenuItem *cut = NULL;
   Gtk::ImageMenuItem *copy = NULL;
   Gtk::ImageMenuItem *paste = NULL;
   Gtk::ImageMenuItem *menu_delete = NULL;
   Gtk::Menu *edit_menu = Gtk::manage(new class Gtk::Menu());
   Gtk::MenuItem *edit = NULL;
   change_name = NULL;
   change_color = NULL;
   Gtk::MenuItem *separator6 = NULL;
   add_computer_player = NULL;
   remove_computer_players = NULL;
   setup_computer_player = NULL;
   show_chat = NULL;
   Gtk::Menu *player_menu = Gtk::manage(new class Gtk::Menu());
   Gtk::MenuItem *player = NULL;
   Gtk::MenuItem *how_to_play = NULL;
   Gtk::MenuItem *about = NULL;
   Gtk::Menu *menuitem4_menu = Gtk::manage(new class Gtk::Menu());
   Gtk::MenuItem *menuitem4 = NULL;
   Gtk::MenuBar *menubar1 = Gtk::manage(new class Gtk::MenuBar());
   game_view = new class game_view();

   Gtk::Overlay *overlay1 = Gtk::manage(new class Gtk::Overlay());

   Gtk::VBox *vbox13 = Gtk::manage(new class Gtk::VBox(false, 6));
   Gtk::VBox *vbox12 = Gtk::manage(new class Gtk::VBox(false, 6));
   Gtk::Label *label49 = Gtk::manage(new class Gtk::Label(_("<b>Players</b>")));
   player_name1 = Gtk::manage(new class Gtk::Label(_("")));
   player_name2 = Gtk::manage(new class Gtk::Label(_("")));
   player_name3 = Gtk::manage(new class Gtk::Label(_("")));
   player_name4 = Gtk::manage(new class Gtk::Label(_("")));
   player_name5 = Gtk::manage(new class Gtk::Label(_("")));
   player_name6 = Gtk::manage(new class Gtk::Label(_("")));
   player_peg1 = new class PegColorSwatch();
   player_peg2 = new class PegColorSwatch();
   player_peg3 = new class PegColorSwatch();
   player_peg4 = new class PegColorSwatch();
   player_peg5 = new class PegColorSwatch();
   player_peg6 = new class PegColorSwatch();

   Gtk::Table *table1 = Gtk::manage(new class Gtk::Table(3, 4, false));
   Gtk::Label *label47 = Gtk::manage(new class Gtk::Label(_("<b>Move</b>")));
   move_counter = Gtk::manage(new class Gtk::Label(_("")));

   message_view = Gtk::manage(new class Gtk::TextView());

   Gtk::ScrolledWindow *scrolledwindow1 = Gtk::manage(new class Gtk::ScrolledWindow());
   chat_entry = Gtk::manage(new class Gtk::Entry());

   chat_area = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::VPaned *vpaned1 = Gtk::manage(new class Gtk::VPaned());
   Gtk::Statusbar *statusbar = Gtk::manage(new class Gtk::Statusbar());
   Gtk::VBox *vbox1 = Gtk::manage(new class Gtk::VBox(false, 0));

   rotate = Gtk::manage(new class Gtk::MenuItem(_("Rot_ate Players"), true));
   rotate->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_A, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   restart_submenu_menu->append(*rotate);

   shuffle = Gtk::manage(new class Gtk::MenuItem(_("Shu_ffle Players"), true));
   shuffle->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_F, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   restart_submenu_menu->append(*shuffle);

   restart_game = Gtk::manage(new class Gtk::MenuItem(_("_Keep Same Order"), true));
   restart_game->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_K, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   restart_submenu_menu->append(*restart_game);

   new_game = Gtk::manage(new class Gtk::MenuItem(_("Host _New Board..."), true));
   new_game->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_N, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   menuitem1_menu->append(*new_game);

   end_game = Gtk::manage(new class Gtk::MenuItem(_("S_top Hosting"), true));
   end_game->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_T, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   menuitem1_menu->append(*end_game);

   separator4 = Gtk::manage(new class Gtk::SeparatorMenuItem());
   menuitem1_menu->append(*separator4);

   join_game = Gtk::manage(new class Gtk::MenuItem(_("_Join a Board..."), true));
   join_game->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_J, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   menuitem1_menu->append(*join_game);

   leave_game = Gtk::manage(new class Gtk::MenuItem(_("_Leave Board"), true));
   leave_game->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_L, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   menuitem1_menu->append(*leave_game);

   separatormenuitem1 = Gtk::manage(new class Gtk::SeparatorMenuItem());
   menuitem1_menu->append(*separatormenuitem1);

   game_settings = Gtk::manage(new class Gtk::MenuItem(_("Change _Game Settings..."), true));
   game_settings->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_G, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   menuitem1_menu->append(*game_settings);

   restart_submenu = Gtk::manage(new class Gtk::MenuItem(_("_Restart Game"), true));
   restart_submenu->set_submenu(*restart_submenu_menu);
   menuitem1_menu->append(*restart_submenu);

   show_chat = Gtk::manage(new class Gtk::MenuItem(_("Show _Chat"), true));
   menuitem1_menu->append(*show_chat);

   separator7 = Gtk::manage(new class Gtk::SeparatorMenuItem());
   menuitem1_menu->append(*separator7);

   quit = Gtk::manage(new class Gtk::ImageMenuItem(Gtk::StockID("gtk-quit")));
   menuitem1_menu->append(*quit);

   undo = Gtk::manage(new class Gtk::ImageMenuItem(*image46, _("_Undo"), true));
   undo->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_Z, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   edit_menu->append(*undo);

   redo = Gtk::manage(new class Gtk::ImageMenuItem(*image47, _("_Redo"), true));
   redo->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_Y, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   edit_menu->append(*redo);

   show_last_move = Gtk::manage(new class Gtk::MenuItem(_("S_how Last Move"), true));
   show_last_move->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_H, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   edit_menu->append(*show_last_move);

   separator5 = Gtk::manage(new class Gtk::SeparatorMenuItem());
   edit_menu->append(*separator5);

   cut = Gtk::manage(new class Gtk::ImageMenuItem(Gtk::StockID("gtk-cut")));
   edit_menu->append(*cut);

   copy = Gtk::manage(new class Gtk::ImageMenuItem(Gtk::StockID("gtk-copy")));
   edit_menu->append(*copy);

   paste = Gtk::manage(new class Gtk::ImageMenuItem(Gtk::StockID("gtk-paste")));
   edit_menu->append(*paste);

   menu_delete = Gtk::manage(new class Gtk::ImageMenuItem(Gtk::StockID("gtk-delete")));
   edit_menu->append(*menu_delete);

   change_name = Gtk::manage(new class Gtk::MenuItem(_("Change Na_me..."), true));
   player_menu->append(*change_name);

   change_color = Gtk::manage(new class Gtk::MenuItem(_("C_hange Color..."), true));
   player_menu->append(*change_color);

   separator6 = Gtk::manage(new class Gtk::SeparatorMenuItem());
   player_menu->append(*separator6);

   add_computer_player = Gtk::manage(new class Gtk::MenuItem(_("_Add Computer Player"), true));
   add_computer_player->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_D, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   player_menu->append(*add_computer_player);

   remove_computer_players = Gtk::manage(new class Gtk::MenuItem(_("R_emove Computer Players"), true));
   remove_computer_players->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_E, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   player_menu->append(*remove_computer_players);

   setup_computer_player = Gtk::manage(new class Gtk::MenuItem(_("Setu_p Computer Player..."), true));
   setup_computer_player->add_accelerator("activate", gmm_data->getAccelGroup(), GDK_KEY_P, Gdk::CONTROL_MASK, Gtk::ACCEL_VISIBLE);
   player_menu->append(*setup_computer_player);

   how_to_play = Gtk::manage(new class Gtk::MenuItem(_("How to _Play"), true));
   menuitem4_menu->append(*how_to_play);

   about = Gtk::manage(new class Gtk::MenuItem(_("_About"), true));
   menuitem4_menu->append(*about);

   menuitem1 = Gtk::manage(new class Gtk::MenuItem(_("_Game"), true));
   menuitem1->set_submenu(*menuitem1_menu);
   menubar1->append(*menuitem1);

   edit = Gtk::manage(new class Gtk::MenuItem(_("_Edit"), true));
   edit->set_submenu(*edit_menu);
   menubar1->append(*edit);

   player = Gtk::manage(new class Gtk::MenuItem(_("_Player"), true));
   player->set_submenu(*player_menu);
   menubar1->append(*player);

   menuitem4 = Gtk::manage(new class Gtk::MenuItem(_("_Help"), true));
   menuitem4->set_submenu(*menuitem4_menu);
   menubar1->append(*menuitem4);
   image46->set_alignment(0.5,0.5);
   image46->set_padding(0,0);
   image47->set_alignment(0.5,0.5);
   image47->set_padding(0,0);
   game_view->set_events(Gdk::EXPOSURE_MASK | Gdk::BUTTON_PRESS_MASK | Gdk::KEY_PRESS_MASK);
   game_view->set_can_focus(true);
   label49->set_alignment(0.5,0.5);
   label49->set_padding(0,0);
   label49->set_justify(Gtk::JUSTIFY_LEFT);
   label49->set_line_wrap(false);
   label49->set_use_markup(true);
   label49->set_selectable(false);
   player_name1->set_alignment(0,0.5);
   player_name1->set_padding(0,0);
   player_name1->set_justify(Gtk::JUSTIFY_LEFT);
   player_name1->set_line_wrap(false);
   player_name1->set_use_markup(false);
   player_name1->set_selectable(false);
   player_name2->set_alignment(0,0.5);
   player_name2->set_padding(0,0);
   player_name2->set_justify(Gtk::JUSTIFY_LEFT);
   player_name2->set_line_wrap(false);
   player_name2->set_use_markup(false);
   player_name2->set_selectable(false);
   player_name3->set_alignment(0,0.5);
   player_name3->set_padding(0,0);
   player_name3->set_justify(Gtk::JUSTIFY_LEFT);
   player_name3->set_line_wrap(false);
   player_name3->set_use_markup(false);
   player_name3->set_selectable(false);
   player_name4->set_alignment(0,0.5);
   player_name4->set_padding(0,0);
   player_name4->set_justify(Gtk::JUSTIFY_LEFT);
   player_name4->set_line_wrap(false);
   player_name4->set_use_markup(false);
   player_name4->set_selectable(false);
   player_name5->set_alignment(0,0.5);
   player_name5->set_padding(0,0);
   player_name5->set_justify(Gtk::JUSTIFY_LEFT);
   player_name5->set_line_wrap(false);
   player_name5->set_use_markup(false);
   player_name5->set_selectable(false);
   player_name6->set_alignment(0,0.5);
   player_name6->set_padding(0,0);
   player_name6->set_justify(Gtk::JUSTIFY_LEFT);
   player_name6->set_line_wrap(false);
   player_name6->set_use_markup(false);
   player_name6->set_selectable(false);
   table1->set_row_spacings(2);
   table1->set_col_spacings(3);
   table1->attach(*player_name1, 1, 2, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*player_name2, 1, 2, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*player_name3, 1, 2, 2, 3, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*player_name4, 3, 4, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*player_name5, 3, 4, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*player_name6, 3, 4, 2, 3, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*player_peg1, 0, 1, 0, 1, Gtk::FILL, Gtk::FILL, 3, 3);
   table1->attach(*player_peg2, 0, 1, 1, 2, Gtk::FILL, Gtk::FILL, 3, 3);
   table1->attach(*player_peg3, 0, 1, 2, 3, Gtk::FILL, Gtk::FILL, 3, 3);
   table1->attach(*player_peg4, 2, 3, 0, 1, Gtk::FILL, Gtk::FILL, 15, 3);
   table1->attach(*player_peg5, 2, 3, 1, 2, Gtk::FILL, Gtk::FILL, 15, 3);
   table1->attach(*player_peg6, 2, 3, 2, 3, Gtk::FILL, Gtk::FILL, 15, 3);
   move_counter->set_alignment(0.5,0.5);
   move_counter->set_padding(0,0);
   move_counter->set_justify(Gtk::JUSTIFY_CENTER);
   move_counter->set_line_wrap(false);
   move_counter->set_use_markup(false);
   move_counter->set_selectable(false);
   label47->set_alignment(0.5,0.5);
   label47->set_padding(0,0);
   label47->set_justify(Gtk::JUSTIFY_LEFT);
   label47->set_line_wrap(false);
   label47->set_use_markup(true);
   label47->set_selectable(false);
   vbox12->pack_start(*label49, Gtk::PACK_SHRINK, 0);
   vbox12->pack_start(*table1, Gtk::PACK_SHRINK, 0);
   vbox12->set_halign(Gtk::ALIGN_START);
   vbox12->set_valign(Gtk::ALIGN_START);
   vbox12->set_margin_top(6);
   vbox12->set_margin_start(24);
   vbox13->pack_start(*label47, Gtk::PACK_SHRINK, 0);
   vbox13->pack_start(*move_counter, Gtk::PACK_SHRINK, 0);
   vbox13->set_halign(Gtk::ALIGN_END);
   vbox13->set_valign(Gtk::ALIGN_START);
   vbox13->set_margin_top(6);
   vbox13->set_margin_end(24);

   vbox12->get_style_context()->add_class("board-info");
   vbox13->get_style_context()->add_class("board-info");
   {
      static Glib::RefPtr<Gtk::CssProvider> board_info_css;
      if (!board_info_css)
      {
         board_info_css = Gtk::CssProvider::create();
         board_info_css->load_from_data(
            ".board-info label { font-size: 150%; color: #000000; }\n"
            ".board-info label:backdrop { color: #000000; opacity: 1; }");
         Gtk::StyleContext::add_provider_for_screen(
            Gdk::Screen::get_default(), board_info_css,
            GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
      }
   }
   overlay1->add(*game_view);
   overlay1->add_overlay(*vbox12);
   overlay1->set_overlay_pass_through(*vbox12, true);
   overlay1->add_overlay(*vbox13);
   overlay1->set_overlay_pass_through(*vbox13, true);
   game_view->evt_board_resized.connect([this, vbox12, vbox13]() {
      double s = game_view->get_scale();
      double bw = game_view->get_base_width() * s;
      double bh = game_view->get_base_height() * s;
      Gdk::Point c = game_view->get_view_center();
      double bx = c.get_x() - bw / 2.0;
      double by = c.get_y() - bh / 2.0;
      int inset = 12;
      vbox12->set_margin_start((int)bx + inset);
      vbox12->set_margin_top((int)by + inset);
      vbox13->set_margin_end((int)(game_view->get_width() - (bx + bw)) + inset + 20);
      vbox13->set_margin_top((int)by + inset);
   });
   message_view->set_editable(false);
   message_view->set_cursor_visible(false);
   message_view->set_pixels_above_lines(0);
   message_view->set_pixels_below_lines(0);
   message_view->set_pixels_inside_wrap(0);
   message_view->set_left_margin(0);
   message_view->set_right_margin(0);
   message_view->set_indent(0);
   message_view->set_wrap_mode(Gtk::WRAP_WORD);
   message_view->set_justification(Gtk::JUSTIFY_LEFT);
   message_view->get_buffer()->set_text(_("Welcome to Chinese Checkers!\n"
		"Choose the 'Host New Board' or 'Join A Board' commands to start playing.\n"
		""));
   scrolledwindow1->set_shadow_type(Gtk::SHADOW_IN);
   scrolledwindow1->set_policy(Gtk::POLICY_NEVER, Gtk::POLICY_AUTOMATIC);
   scrolledwindow1->set_size_request(-1, 120);
   scrolledwindow1->property_window_placement().set_value(Gtk::CORNER_TOP_LEFT);
   scrolledwindow1->add(*message_view);
   chat_entry->set_can_focus(true);
   chat_entry->set_visibility(true);
   chat_entry->set_editable(true);
   chat_entry->set_max_length(0);
   chat_entry->set_text(_(""));
   chat_entry->set_has_frame(true);
   chat_entry->set_activates_default(false);
   chat_area->set_border_width(3);
   chat_area->pack_start(*scrolledwindow1);
   chat_area->pack_start(*chat_entry, Gtk::PACK_SHRINK, 0);
   vpaned1->set_can_focus(true);
   vpaned1->pack1(*overlay1, Gtk::EXPAND|Gtk::SHRINK);
   vpaned1->pack2(*chat_area, Gtk::EXPAND|Gtk::SHRINK);
   vbox1->pack_start(*menubar1, Gtk::PACK_SHRINK, 0);
   vbox1->pack_start(*vpaned1);
   vbox1->pack_start(*statusbar, Gtk::PACK_SHRINK, 0);
   main_win->set_title(_("Chinese Checkers"));
   int board_width = 0;
   int board_height = 0;
   game_view->get_size_request(board_width, board_height);
   main_win->set_default_size(board_width + 120, board_height + 200);
   main_win->set_size_request(board_width + 20, board_height + 120);
   main_win->set_modal(false);
   main_win->property_window_position().set_value(Gtk::WIN_POS_NONE);
   main_win->set_resizable(true);
   main_win->property_destroy_with_parent().set_value(true);
   main_win->add(*vbox1);
   new_game->show();
   end_game->show();
   separator4->show();
   join_game->show();
   leave_game->show();
   separatormenuitem1->show();
   game_settings->show();
   rotate->show();
   shuffle->show();
   restart_game->show();
   restart_submenu->show();
   show_chat->show();
   separator7->show();
   quit->show();
   menuitem1->show();
   image46->show();
   undo->show();
   image47->show();
   redo->show();
   show_last_move->show();
   separator5->show();
   cut->show();
   copy->show();
   paste->show();
   menu_delete->show();
   edit->show();
   change_name->show();
   change_color->show();
   separator6->show();
   add_computer_player->show();
   remove_computer_players->show();
   setup_computer_player->show();
   player->show();
   how_to_play->show();
   about->show();
   menuitem4->show();
   menubar1->show();
   game_view->show();
   overlay1->show();
   vbox12->show();
   vbox13->show();
   label49->show();
   player_name1->show();
   player_name2->show();
   player_name3->show();
   player_name4->show();
   player_name5->show();
   player_name6->show();
   player_peg1->show();
   player_peg2->show();
   player_peg3->show();
   player_peg4->show();
   player_peg5->show();
   player_peg6->show();
   table1->show();
   move_counter->show();
   label47->show();
   message_view->show();
   scrolledwindow1->show();
   chat_entry->show();
   vpaned1->show();
   statusbar->hide();
   vbox1->show();
   main_win->show();
   new_game->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_new_game_activate), false);
   end_game->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_end_game_activate), false);
   join_game->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_join_game_activate), false);
   leave_game->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_leave_game_activate), false);
   game_settings->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_game_settings_activate), false);
   rotate->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_rotate_activate), false);
   shuffle->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_shuffle_activate), false);
   restart_game->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_restart_game_activate), false);
   show_chat->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_show_chat_activate), false);
   quit->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_quit_activate), false);
   undo->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_undo_activate), false);
   redo->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_redo_activate), false);
   show_last_move->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_show_last_move_activate), false);
   cut->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_cut_activate), false);
   copy->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_copy_activate), false);
   paste->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_paste_activate), false);
   menu_delete->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_delete_activate), false);
   change_name->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_change_name_activate), false);
   change_color->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_change_color_activate), false);
   add_computer_player->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_add_computer_player_activate), false);
   remove_computer_players->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_remove_computer_players_activate), false);
   setup_computer_player->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_setup_computer_player_activate), false);
   how_to_play->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_how_to_play_activate), false);
   about->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_about_activate), false);
   chat_entry->signal_activate().connect(sigc::mem_fun(this, &main_win_glade::on_chat_entry_activate), false);
}

main_win_glade::~main_win_glade()
{  delete game_view;
   delete player_peg1;
   delete player_peg2;
   delete player_peg3;
   delete player_peg4;
   delete player_peg5;
   delete player_peg6;
   delete gmm_data;
}
