// generated 2006/4/13 13:56:33 PDT by benjie@paddy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/benjie/projects/cheech/cheech.glade
// for gtk 2.8.6 and gtkmm 2.8.0
//
// Please modify the corresponding derived classes in ./src/name_win.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
//#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "name_win_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/label.h>
#include <gtkmm/box.h>
#include <gtkmm/button.h>
#include <gtkmm/image.h>
#include <gtkmm/alignment.h>
#include <gtkmm/buttonbox.h>

name_win_glade::name_win_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{

   Gtk::Window *name_win = this;
   gmm_data = new GlademmData(get_accel_group());
   change_label = Gtk::manage(new class Gtk::Label(_("<b>The name %1 is already in use.\n"
		"Please choose a differnt name.</b>")));

   Gtk::Label *label53 = Gtk::manage(new class Gtk::Label(_("Name:")));
   name_entry = Gtk::manage(new class Gtk::Entry());

   Gtk::HBox *hbox7 = Gtk::manage(new class Gtk::HBox(false, 0));
   Gtk::Button *cancel_button = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   Gtk::Image *image16 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-apply"), Gtk::IconSize(4)));
   Gtk::Label *label52 = Gtk::manage(new class Gtk::Label(_("Change Name")));
   Gtk::HBox *hbox6 = Gtk::manage(new class Gtk::HBox(false, 2));
   Gtk::Alignment *alignment18 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 0, 0));
   Gtk::Button *change_button = Gtk::manage(new class Gtk::Button());
   Gtk::HButtonBox *hbuttonbox9 = Gtk::manage(new class Gtk::HButtonBox(Gtk::BUTTONBOX_END, 6));
   Gtk::VBox *vbox13 = Gtk::manage(new class Gtk::VBox(false, 6));
   change_label->set_alignment(0.5,0.5);
   change_label->set_padding(0,0);
   change_label->set_justify(Gtk::JUSTIFY_CENTER);
   change_label->set_line_wrap(false);
   change_label->set_use_markup(true);
   change_label->set_selectable(false);
   label53->set_alignment(0.5,0.5);
   label53->set_padding(0,0);
   label53->set_justify(Gtk::JUSTIFY_LEFT);
   label53->set_line_wrap(false);
   label53->set_use_markup(false);
   label53->set_selectable(false);
   name_entry->set_flags(Gtk::CAN_FOCUS);
   name_entry->set_visibility(true);
   name_entry->set_editable(true);
   name_entry->set_max_length(0);
   name_entry->set_text(_(""));
   name_entry->set_has_frame(true);
   name_entry->set_activates_default(false);
   hbox7->pack_start(*label53, Gtk::PACK_SHRINK, 0);
   hbox7->pack_start(*name_entry);
   cancel_button->set_flags(Gtk::CAN_FOCUS);
   cancel_button->set_flags(Gtk::CAN_DEFAULT);
   cancel_button->set_relief(Gtk::RELIEF_NORMAL);
   image16->set_alignment(0.5,0.5);
   image16->set_padding(0,0);
   label52->set_alignment(0.5,0.5);
   label52->set_padding(0,0);
   label52->set_justify(Gtk::JUSTIFY_LEFT);
   label52->set_line_wrap(false);
   label52->set_use_markup(false);
   label52->set_selectable(false);
   hbox6->pack_start(*image16, Gtk::PACK_SHRINK, 0);
   hbox6->pack_start(*label52, Gtk::PACK_SHRINK, 0);
   alignment18->add(*hbox6);
   change_button->set_flags(Gtk::CAN_FOCUS);
   change_button->set_flags(Gtk::CAN_DEFAULT);
   change_button->set_relief(Gtk::RELIEF_NORMAL);
   change_button->add(*alignment18);
   hbuttonbox9->pack_start(*cancel_button);
   hbuttonbox9->pack_start(*change_button);
   vbox13->set_border_width(6);
   vbox13->pack_start(*change_label, Gtk::PACK_SHRINK, 0);
   vbox13->pack_start(*hbox7);
   vbox13->pack_start(*hbuttonbox9);
   name_win->set_title(_("Change Your Name"));
   name_win->set_modal(false);
   name_win->property_window_position().set_value(Gtk::WIN_POS_NONE);
   name_win->set_resizable(true);
   name_win->property_destroy_with_parent().set_value(false);
   name_win->add(*vbox13);
   label53->show();
   name_entry->show();
   hbox7->show();
   cancel_button->show();
   image16->show();
   label52->show();
   hbox6->show();
   alignment18->show();
   change_button->show();
   hbuttonbox9->show();
   vbox13->show();
   name_entry->signal_activate().connect(sigc::mem_fun(this, &name_win_glade::on_name_entry_activate), false);
   cancel_button->signal_clicked().connect(sigc::mem_fun(this, &name_win_glade::on_cancel_button_clicked), false);
   change_button->signal_clicked().connect(sigc::mem_fun(this, &name_win_glade::on_change_button_clicked), false);
   change_button->grab_default();
}

name_win_glade::~name_win_glade()
{  delete gmm_data;
}
