// generated 2006/4/4 19:20:50 EST by benjie@paddy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/benjie/projects/cheech/cheech.glade
// for gtk 2.8.6 and gtkmm 2.8.0
//
// Please modify the corresponding derived classes in ./src/name_win.hh and./src/name_win.cc

#ifndef _NAME_WIN_GLADE_HH
#  define _NAME_WIN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/label.h>
#include <gtkmm/entry.h>

class name_win_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Label * change_label;
        class Gtk::Entry * name_entry;
        
        name_win_glade();
        
        ~name_win_glade();
private:
        virtual void on_name_entry_activate() = 0;
        virtual void on_cancel_button_clicked() = 0;
        virtual void on_change_button_clicked() = 0;
};
#endif
