// generated 2006/5/26 14:41:42 PDT by benjie@paddy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/benjie/projects/cheech/cheech.glade
// for gtk 2.8.6 and gtkmm 2.8.0
//
// Please modify the corresponding derived classes in ./src/new_game_win.hh and./src/new_game_win.cc

#ifndef _NEW_GAME_WIN_GLADE_HH
#  define _NEW_GAME_WIN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/entry.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/spinbutton.h>
#include <gtkmm/button.h>
#include "GtkComboBoxEntryText.hh"
#include <gtkmm/notebook.h>

class new_game_win_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Entry * name_entry;
        class Gtk::RadioButton * orange;
        class Gtk::RadioButton * yellow;
        class Gtk::RadioButton * white;
        class Gtk::RadioButton * blue;
        class Gtk::RadioButton * purple;
        class Gtk::RadioButton * black;
        class Gtk::RadioButton * red;
        class Gtk::RadioButton * green;
        class Gtk::CheckButton * spectator;
        class Gtk::Entry * host_port_entry;
        class Gtk::SpinButton * num_players;
        class Gtk::CheckButton * long_jumps;
        class Gtk::CheckButton * hop_others;
        class Gtk::CheckButton * stop_others;
        class Gtk::CheckButton * cheechweb;
        class Gtk::Entry * cheechweb_port_entry;
        class Gtk::Button * host_button;
        class Gtk::Entry * join_port_entry;
        class GtkComboBoxEntryText * join_host_entry;
        class Gtk::Button * join_button;
        class Gtk::Notebook * role_notebook;
        
        new_game_win_glade();
        
        ~new_game_win_glade();
private:
        virtual void on_name_entry_activate() = 0;
        virtual void on_host_port_entry_activate() = 0;
        virtual void on_num_players_activate() = 0;
        virtual void on_cheechweb_toggled() = 0;
        virtual void on_cheechweb_port_entry_activate() = 0;
        virtual void on_host_cancel_button_clicked() = 0;
        virtual void on_host_button_clicked() = 0;
        virtual void on_join_port_entry_activate() = 0;
        virtual void on_join_cancel_button_clicked() = 0;
        virtual void on_join_button_clicked() = 0;
};
#endif
