// generated 2006/4/13 14:42:35 PDT by benjie@paddy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/benjie/projects/cheech/cheech.glade
// for gtk 2.8.6 and gtkmm 2.8.0
//
// Please modify the corresponding derived classes in ./src/setup_bot_win.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
//#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "setup_bot_win_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/label.h>
#include <gtkmm/table.h>
#include <gtkmm/adjustment.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/box.h>
#include <gtkmm/alignment.h>
#include <gtkmm/frame.h>
#include <gtkmm/image.h>

setup_bot_win_glade::setup_bot_win_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{

   Gtk::Window *setup_bot_win = this;
   gmm_data = new GlademmData(get_accel_group());

   Gtk::Label *label59 = Gtk::manage(new class Gtk::Label(_("Type:")));
   Gtk::Label *label54 = Gtk::manage(new class Gtk::Label(_("Name:")));
   name_entry = Gtk::manage(new class Gtk::Entry());
   type_box = new class GtkComboBoxText();

   Gtk::Table *table8 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Label *label61 = Gtk::manage(new class Gtk::Label(_("Move Done:")));
   Gtk::Label *label62 = Gtk::manage(new class Gtk::Label(_("Move Step:")));
   Gtk::Label *label63 = Gtk::manage(new class Gtk::Label(_("Thinking:")));
   Gtk::Adjustment *done_scale_adj = Gtk::manage(new class Gtk::Adjustment(0.600000023842, 0, 2, 0.10000000149, 0.5, 0));
   done_scale = Gtk::manage(new class Gtk::HScale(*done_scale_adj));

   Gtk::Adjustment *move_scale_adj = Gtk::manage(new class Gtk::Adjustment(0.40000000596, 0, 2, 0.10000000149, 0.5, 0));
   move_scale = Gtk::manage(new class Gtk::HScale(*move_scale_adj));

   Gtk::Adjustment *think_scale_adj = Gtk::manage(new class Gtk::Adjustment(0, 0, 2, 0.10000000149, 0.5, 0));
   think_scale = Gtk::manage(new class Gtk::HScale(*think_scale_adj));

   Gtk::Table *table9 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Button *defaults = Gtk::manage(new class Gtk::Button(_("Use Default Delays")));
   Gtk::HButtonBox *hbuttonbox11 = Gtk::manage(new class Gtk::HButtonBox(Gtk::BUTTONBOX_END, 0));
   Gtk::VBox *vbox16 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Alignment *alignment22 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label60 = Gtk::manage(new class Gtk::Label(_("<b>Delays</b>")));
   Gtk::Frame *frame13 = Gtk::manage(new class Gtk::Frame());
   Gtk::VBox *vbox15 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Alignment *alignment19 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label56 = Gtk::manage(new class Gtk::Label(_("<b>Computer Player</b>")));
   Gtk::Frame *frame12 = Gtk::manage(new class Gtk::Frame());
   Gtk::Image *image50 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-add"), Gtk::IconSize(4)));
   Gtk::Label *label70 = Gtk::manage(new class Gtk::Label(_("Add Computer Player")));
   Gtk::HBox *hbox13 = Gtk::manage(new class Gtk::HBox(false, 2));
   Gtk::Alignment *alignment27 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 0, 0));
   add_button = Gtk::manage(new class Gtk::Button());

   Gtk::Image *image49 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-remove"), Gtk::IconSize(4)));
   Gtk::Label *label69 = Gtk::manage(new class Gtk::Label(_("Remove Computer Players")));
   Gtk::HBox *hbox12 = Gtk::manage(new class Gtk::HBox(false, 2));
   Gtk::Alignment *alignment26 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 0, 0));
   remove_button = Gtk::manage(new class Gtk::Button());

   Gtk::Image *image48 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-close"), Gtk::IconSize(4)));
   Gtk::Label *label68 = Gtk::manage(new class Gtk::Label(_("OK")));
   Gtk::HBox *hbox11 = Gtk::manage(new class Gtk::HBox(false, 2));
   Gtk::Alignment *alignment25 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 0, 0));
   Gtk::Button *ok_button = Gtk::manage(new class Gtk::Button());
   Gtk::HButtonBox *hbuttonbox10 = Gtk::manage(new class Gtk::HButtonBox(Gtk::BUTTONBOX_END, 6));
   Gtk::VBox *vbox14 = Gtk::manage(new class Gtk::VBox(false, 0));
   label59->set_alignment(0.5,0.5);
   label59->set_padding(0,0);
   label59->set_justify(Gtk::JUSTIFY_RIGHT);
   label59->set_line_wrap(false);
   label59->set_use_markup(false);
   label59->set_selectable(false);
   label54->set_alignment(0.5,0.5);
   label54->set_padding(0,0);
   label54->set_justify(Gtk::JUSTIFY_RIGHT);
   label54->set_line_wrap(false);
   label54->set_use_markup(false);
   label54->set_selectable(false);
   name_entry->set_flags(Gtk::CAN_FOCUS);
   name_entry->set_visibility(true);
   name_entry->set_editable(true);
   name_entry->set_max_length(0);
   name_entry->set_text(_(""));
   name_entry->set_has_frame(true);
   name_entry->set_activates_default(false);
   table8->set_border_width(6);
   table8->set_row_spacings(3);
   table8->set_col_spacings(3);
   table8->attach(*label59, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table8->attach(*label54, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table8->attach(*name_entry, 1, 2, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table8->attach(*type_box, 1, 2, 0, 1, Gtk::FILL, Gtk::FILL, 0, 0);
   label61->set_alignment(0.5,0.5);
   label61->set_padding(0,0);
   label61->set_justify(Gtk::JUSTIFY_RIGHT);
   label61->set_line_wrap(false);
   label61->set_use_markup(false);
   label61->set_selectable(false);
   label62->set_alignment(0.5,0.5);
   label62->set_padding(0,0);
   label62->set_justify(Gtk::JUSTIFY_RIGHT);
   label62->set_line_wrap(false);
   label62->set_use_markup(false);
   label62->set_selectable(false);
   label63->set_alignment(0.5,0.5);
   label63->set_padding(0,0);
   label63->set_justify(Gtk::JUSTIFY_RIGHT);
   label63->set_line_wrap(false);
   label63->set_use_markup(false);
   label63->set_selectable(false);
   done_scale->set_flags(Gtk::CAN_FOCUS);
   done_scale->set_update_policy(Gtk::UPDATE_CONTINUOUS);
   done_scale->set_inverted(false);
   done_scale->set_digits(3);
   done_scale->set_draw_value(true);
   done_scale->set_value_pos(Gtk::POS_TOP);
   move_scale->set_flags(Gtk::CAN_FOCUS);
   move_scale->set_update_policy(Gtk::UPDATE_CONTINUOUS);
   move_scale->set_inverted(false);
   move_scale->set_digits(3);
   move_scale->set_draw_value(true);
   move_scale->set_value_pos(Gtk::POS_TOP);
   think_scale->set_flags(Gtk::CAN_FOCUS);
   think_scale->set_update_policy(Gtk::UPDATE_CONTINUOUS);
   think_scale->set_inverted(false);
   think_scale->set_digits(3);
   think_scale->set_draw_value(true);
   think_scale->set_value_pos(Gtk::POS_TOP);
   table9->set_row_spacings(0);
   table9->set_col_spacings(0);
   table9->attach(*label61, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table9->attach(*label62, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table9->attach(*label63, 0, 1, 2, 3, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table9->attach(*done_scale, 1, 2, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::FILL, 0, 0);
   table9->attach(*move_scale, 1, 2, 1, 2, Gtk::FILL, Gtk::FILL, 0, 0);
   table9->attach(*think_scale, 1, 2, 2, 3, Gtk::FILL, Gtk::FILL, 0, 0);
   defaults->set_flags(Gtk::CAN_FOCUS);
   defaults->set_flags(Gtk::CAN_DEFAULT);
   defaults->set_relief(Gtk::RELIEF_NORMAL);
   hbuttonbox11->pack_start(*defaults);
   vbox16->pack_start(*table9);
   vbox16->pack_start(*hbuttonbox11);
   alignment22->set_border_width(6);
   alignment22->add(*vbox16);
   label60->set_alignment(0.5,0.5);
   label60->set_padding(0,0);
   label60->set_justify(Gtk::JUSTIFY_LEFT);
   label60->set_line_wrap(false);
   label60->set_use_markup(true);
   label60->set_selectable(false);
   frame13->set_border_width(6);
   frame13->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame13->set_label_align(0,0.5);
   frame13->add(*alignment22);
   frame13->set_label_widget(*label60);
   vbox15->pack_start(*table8);
   vbox15->pack_start(*frame13);
   alignment19->add(*vbox15);
   label56->set_alignment(0.5,0.5);
   label56->set_padding(0,0);
   label56->set_justify(Gtk::JUSTIFY_LEFT);
   label56->set_line_wrap(false);
   label56->set_use_markup(true);
   label56->set_selectable(false);
   frame12->set_border_width(3);
   frame12->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame12->set_label_align(0,0.5);
   frame12->add(*alignment19);
   frame12->set_label_widget(*label56);
   image50->set_alignment(0.5,0.5);
   image50->set_padding(0,0);
   label70->set_alignment(0.5,0.5);
   label70->set_padding(0,0);
   label70->set_justify(Gtk::JUSTIFY_LEFT);
   label70->set_line_wrap(false);
   label70->set_use_markup(false);
   label70->set_selectable(false);
   hbox13->pack_start(*image50, Gtk::PACK_SHRINK, 0);
   hbox13->pack_start(*label70, Gtk::PACK_SHRINK, 0);
   alignment27->add(*hbox13);
   add_button->set_sensitive(false);
   add_button->set_flags(Gtk::CAN_FOCUS);
   add_button->set_flags(Gtk::CAN_DEFAULT);
   add_button->set_relief(Gtk::RELIEF_NORMAL);
   add_button->add(*alignment27);
   image49->set_alignment(0.5,0.5);
   image49->set_padding(0,0);
   label69->set_alignment(0.5,0.5);
   label69->set_padding(0,0);
   label69->set_justify(Gtk::JUSTIFY_LEFT);
   label69->set_line_wrap(false);
   label69->set_use_markup(false);
   label69->set_selectable(false);
   hbox12->pack_start(*image49, Gtk::PACK_SHRINK, 0);
   hbox12->pack_start(*label69, Gtk::PACK_SHRINK, 0);
   alignment26->add(*hbox12);
   remove_button->set_flags(Gtk::CAN_FOCUS);
   remove_button->set_flags(Gtk::CAN_DEFAULT);
   remove_button->set_relief(Gtk::RELIEF_NORMAL);
   remove_button->add(*alignment26);
   image48->set_alignment(0.5,0.5);
   image48->set_padding(0,0);
   label68->set_alignment(0.5,0.5);
   label68->set_padding(0,0);
   label68->set_justify(Gtk::JUSTIFY_LEFT);
   label68->set_line_wrap(false);
   label68->set_use_markup(false);
   label68->set_selectable(false);
   hbox11->pack_start(*image48, Gtk::PACK_SHRINK, 0);
   hbox11->pack_start(*label68, Gtk::PACK_SHRINK, 0);
   alignment25->add(*hbox11);
   ok_button->set_flags(Gtk::CAN_FOCUS);
   ok_button->set_flags(Gtk::CAN_DEFAULT);
   ok_button->set_relief(Gtk::RELIEF_NORMAL);
   ok_button->add(*alignment25);
   hbuttonbox10->set_border_width(6);
   hbuttonbox10->pack_start(*add_button);
   hbuttonbox10->pack_start(*remove_button);
   hbuttonbox10->pack_start(*ok_button);
   vbox14->set_border_width(6);
   vbox14->pack_start(*frame12);
   vbox14->pack_start(*hbuttonbox10);
   setup_bot_win->set_title(_("Computer Player Setup"));
   setup_bot_win->set_modal(false);
   setup_bot_win->property_window_position().set_value(Gtk::WIN_POS_NONE);
   setup_bot_win->set_resizable(true);
   setup_bot_win->property_destroy_with_parent().set_value(false);
   setup_bot_win->add(*vbox14);
   label59->show();
   label54->show();
   name_entry->show();
   type_box->show();
   table8->show();
   label61->show();
   label62->show();
   label63->show();
   done_scale->show();
   move_scale->show();
   think_scale->show();
   table9->show();
   defaults->show();
   hbuttonbox11->show();
   vbox16->show();
   alignment22->show();
   label60->show();
   frame13->show();
   vbox15->show();
   alignment19->show();
   label56->show();
   frame12->show();
   image50->show();
   label70->show();
   hbox13->show();
   alignment27->show();
   add_button->show();
   image49->show();
   label69->show();
   hbox12->show();
   alignment26->show();
   remove_button->show();
   image48->show();
   label68->show();
   hbox11->show();
   alignment25->show();
   ok_button->show();
   hbuttonbox10->show();
   vbox14->show();
   defaults->signal_clicked().connect(sigc::mem_fun(this, &setup_bot_win_glade::on_defaults_activate), false);
   add_button->signal_clicked().connect(sigc::mem_fun(this, &setup_bot_win_glade::on_add_button_activate), false);
   remove_button->signal_clicked().connect(sigc::mem_fun(this, &setup_bot_win_glade::on_remove_button_activate), false);
   ok_button->signal_clicked().connect(sigc::mem_fun(this, &setup_bot_win_glade::on_ok_button_activate), false);
   add_button->grab_default();
}

setup_bot_win_glade::~setup_bot_win_glade()
{  delete type_box;
   delete gmm_data;
}
