// generated 2006/4/10 18:28:01 EST by benjie@paddy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/benjie/projects/cheech/cheech.glade
// for gtk 2.8.6 and gtkmm 2.8.0
//
// Please modify the corresponding derived classes in ./src/setup_bot_win.hh and./src/setup_bot_win.cc

#ifndef _SETUP_BOT_WIN_GLADE_HH
#  define _SETUP_BOT_WIN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/entry.h>
#include "GtkComboBoxText.hh"
#include <gtkmm/scale.h>
#include <gtkmm/button.h>

class setup_bot_win_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Entry * name_entry;
        class GtkComboBoxText * type_box;
        class Gtk::HScale * done_scale;
        class Gtk::HScale * move_scale;
        class Gtk::HScale * think_scale;
        class Gtk::Button * add_button;
        class Gtk::Button * remove_button;
        
        setup_bot_win_glade();
        
        ~setup_bot_win_glade();
private:
        virtual void on_defaults_activate() = 0;
        virtual void on_add_button_activate() = 0;
        virtual void on_remove_button_activate() = 0;
        virtual void on_ok_button_activate() = 0;
};
#endif
