## Process this file with automake to produce Makefile.in

ajaxdir = $(datadir)/$(PACKAGE)/cheechweb

dist_ajax_DATA = \
	15D93A1FDFF22779A23A08278F59A953.cache.html \
	15D93A1FDFF22779A23A08278F59A953.cache.xml \
	1E757BA6FE1CD6DCCF0EF6EE1F1916BE.cache.html \
	1E757BA6FE1CD6DCCF0EF6EE1F1916BE.cache.xml \
	2DA9E259B1E54AEBAB6942D8775C1A1D.cache.html \
	2DA9E259B1E54AEBAB6942D8775C1A1D.cache.xml \
	93B61057D4F4E4E4CFEEDA7767D9C7D2.cache.html \
	93B61057D4F4E4E4CFEEDA7767D9C7D2.cache.xml \
	cheech.css \
	cheechweb.html \
	chinesecheckers.html \
	com.benjie.cheech.nocache.html \
	EED299CE3177E3D3B98087A75E716F40.cache.html \
	EED299CE3177E3D3B98087A75E716F40.cache.xml \
	gwt.js \
	history.html \
	index.html
